export const clubs = [
  {
    fullName: 'Arsenal FC',
    commonName: 'Arsenal',
    shortName: 'ARS',
    country: 'England',
    clubLogoUrl: 'https://cdn-team-logos.theathletic.com/cdn-cgi/image/width=48,format=auto/https://cdn-team-logos.theathletic.com/team-logo-651-300x300.png',
    stadium: 'Emirates Stadium',
  },
  {
    fullName: 'Chelsea FC',
    commonName: 'Chelsea',
    shortName: 'CHE',
    country: 'England',
    clubLogoUrl: 'https://cdn-team-logos.theathletic.com/cdn-cgi/image/width=48,format=auto/https://cdn-team-logos.theathletic.com/team-logo-652-300x300.png',
    stadium: 'Stamford Bridge',
  },
  {
    fullName: 'Everton',
    commonName: 'Everton',
    shortName: 'EVE',
    country: 'England',
    clubLogoUrl: 'https://cdn-team-logos.theathletic.com/cdn-cgi/image/width=48,format=auto/https://cdn-team-logos.theathletic.com/team-logo-677-300x300.png',
    stadium: 'Goodison Park',
  },
  {
    fullName: 'Leicester City',
    commonName: 'Leicester',
    shortName: 'LEC',
    country: 'England',
    clubLogoUrl: 'https://cdn-team-logos.theathletic.com/cdn-cgi/image/width=48,format=auto/https://cdn-team-logos.theathletic.com/team-logo-678-300x300.png',
    stadium: 'King Power Stadium',
  },
  {
    fullName: 'Liverpool FC',
    commonName: 'Liverpool',
    shortName: 'LVP',
    country: 'England',
    clubLogoUrl: 'https://cdn-team-logos.theathletic.com/cdn-cgi/image/width=48,format=auto/https://cdn-team-logos.theathletic.com/team-logo-653-300x300.png',
    stadium: 'Anfield Road',
  },
  {
    fullName: 'Manchester City FC',
    commonName: 'Manchester City',
    shortName: 'MCI',
    country: 'England',
    clubLogoUrl: 'https://cdn-team-logos.theathletic.com/cdn-cgi/image/width=48,format=auto/https://cdn-team-logos.theathletic.com/team-logo-654-300x300.png',
    stadium: 'Etihad Stadium',
  },
  {
    fullName: 'Manchester United FC',
    commonName: 'Manchester United',
    shortName: 'MUN',
    country: 'England',
    clubLogoUrl: 'https://cdn-team-logos.theathletic.com/cdn-cgi/image/width=48,format=auto/https://cdn-team-logos.theathletic.com/team-logo-655-300x300.png',
    stadium: 'Old Trafford',
  },
  {
    fullName: 'Tottenham Hotspur',
    commonName: 'Tottenham',
    shortName: 'TOT',
    country: 'England',
    clubLogoUrl: 'https://cdn-team-logos.theathletic.com/cdn-cgi/image/width=48,format=auto/https://cdn-team-logos.theathletic.com/team-logo-656-300x300.png',
    stadium: 'Tottenham Hotspur Stadium',
  },
  {
    fullName: 'Arsenal FC',
    commonName: 'Arsenal',
    shortName: 'ARS',
    country: 'England',
    clubLogoUrl: 'https://cdn-team-logos.theathletic.com/cdn-cgi/image/width=48,format=auto/https://cdn-team-logos.theathletic.com/team-logo-651-300x300.png',
    stadium: 'Emirates Stadium',
  },
  {
    fullName: 'Chelsea FC',
    commonName: 'Chelsea',
    shortName: 'CHE',
    country: 'England',
    clubLogoUrl: 'https://cdn-team-logos.theathletic.com/cdn-cgi/image/width=48,format=auto/https://cdn-team-logos.theathletic.com/team-logo-652-300x300.png',
    stadium: 'Stamford Bridge',
  },
  {
    fullName: 'Everton',
    commonName: 'Everton',
    shortName: 'EVE',
    country: 'England',
    clubLogoUrl: 'https://cdn-team-logos.theathletic.com/cdn-cgi/image/width=48,format=auto/https://cdn-team-logos.theathletic.com/team-logo-677-300x300.png',
    stadium: 'Goodison Park',
  },
  {
    fullName: 'Leicester City',
    commonName: 'Leicester',
    shortName: 'LEC',
    country: 'England',
    clubLogoUrl: 'https://cdn-team-logos.theathletic.com/cdn-cgi/image/width=48,format=auto/https://cdn-team-logos.theathletic.com/team-logo-678-300x300.png',
    stadium: 'King Power Stadium',
  },
  {
    fullName: 'Liverpool FC',
    commonName: 'Liverpool',
    shortName: 'LVP',
    country: 'England',
    clubLogoUrl: 'https://cdn-team-logos.theathletic.com/cdn-cgi/image/width=48,format=auto/https://cdn-team-logos.theathletic.com/team-logo-653-300x300.png',
    stadium: 'Anfield Road',
  },
  {
    fullName: 'Manchester City FC',
    commonName: 'Manchester City',
    shortName: 'MCI',
    country: 'England',
    clubLogoUrl: 'https://cdn-team-logos.theathletic.com/cdn-cgi/image/width=48,format=auto/https://cdn-team-logos.theathletic.com/team-logo-654-300x300.png',
    stadium: 'Etihad Stadium',
  },
  {
    fullName: 'Manchester United FC',
    commonName: 'Manchester United',
    shortName: 'MUN',
    country: 'England',
    clubLogoUrl: 'https://cdn-team-logos.theathletic.com/cdn-cgi/image/width=48,format=auto/https://cdn-team-logos.theathletic.com/team-logo-655-300x300.png',
    stadium: 'Old Trafford',
  },
  {
    fullName: 'Tottenham Hotspur',
    commonName: 'Tottenham',
    shortName: 'TOT',
    country: 'England',
    clubLogoUrl: 'https://cdn-team-logos.theathletic.com/cdn-cgi/image/width=48,format=auto/https://cdn-team-logos.theathletic.com/team-logo-656-300x300.png',
    stadium: 'Tottenham Hotspur Stadium',
  },
  {
    fullName: 'Liverpool FC',
    commonName: 'Liverpool',
    shortName: 'LVP',
    country: 'England',
    clubLogoUrl: 'https://cdn-team-logos.theathletic.com/cdn-cgi/image/width=48,format=auto/https://cdn-team-logos.theathletic.com/team-logo-653-300x300.png',
    stadium: 'Anfield Road',
  },
  {
    fullName: 'Manchester City FC',
    commonName: 'Manchester City',
    shortName: 'MCI',
    country: 'England',
    clubLogoUrl: 'https://cdn-team-logos.theathletic.com/cdn-cgi/image/width=48,format=auto/https://cdn-team-logos.theathletic.com/team-logo-654-300x300.png',
    stadium: 'Etihad Stadium',
  },
  {
    fullName: 'Manchester United FC',
    commonName: 'Manchester United',
    shortName: 'MUN',
    country: 'England',
    clubLogoUrl: 'https://cdn-team-logos.theathletic.com/cdn-cgi/image/width=48,format=auto/https://cdn-team-logos.theathletic.com/team-logo-655-300x300.png',
    stadium: 'Old Trafford',
  },
  {
    fullName: 'Tottenham Hotspur',
    commonName: 'Tottenham',
    shortName: 'TOT',
    country: 'England',
    clubLogoUrl: 'https://cdn-team-logos.theathletic.com/cdn-cgi/image/width=48,format=auto/https://cdn-team-logos.theathletic.com/team-logo-656-300x300.png',
    stadium: 'Tottenham Hotspur Stadium',
  },

  {
    fullName: 'Bayern Munchen',
    commonName: 'Bayern',
    shortName: 'BMN',
    country: 'Germany',
    clubLogoUrl: 'https://cdn-team-logos.theathletic.com/cdn-cgi/image/width=1920,format=auto/https://cdn-team-logos.theathletic.com/team-logo-659-300x300.png',
    stadium: 'Allianz Arena',
  },
  {
    fullName: 'Borussia Dortmund',
    commonName: 'Dortmund',
    shortName: 'BVB',
    country: 'Germany',
    clubLogoUrl: 'https://cdn-team-logos.theathletic.com/cdn-cgi/image/width=48,format=auto/https://cdn-team-logos.theathletic.com/team-logo-726-300x300.png',
    stadium: 'Signa Iduna Park',
  },
  {
    fullName: 'FC Barcelona',
    commonName: 'Barcelona',
    shortName: 'BAR',
    country: 'Spain',
    clubLogoUrl: 'https://cdn-team-logos.theathletic.com/cdn-cgi/image/width=48,format=auto/https://cdn-team-logos.theathletic.com/team-logo-657-300x300.png',
    stadium: 'Camp Nou',
  },
  {
    fullName: 'Atletico Madrid',
    commonName: 'Atletico',
    shortName: 'ATM',
    country: 'Spain',
    clubLogoUrl: 'https://cdn-team-logos.theathletic.com/cdn-cgi/image/width=48,format=auto/https://cdn-team-logos.theathletic.com/team-logo-765-300x300.png',
    stadium: 'Estádio Cívitas Metropolitano',
  },
  {
    fullName: 'FC Real Madrid',
    commonName: 'Real Madrid',
    shortName: 'RMA',
    country: 'Spain',
    clubLogoUrl: 'https://cdn-team-logos.theathletic.com/cdn-cgi/image/width=48,format=auto/https://cdn-team-logos.theathletic.com/team-logo-658-300x300.png',
    stadium: 'Camp Nou',
  },
  {
    fullName: 'Sevilla FC',
    commonName: 'Sevilla',
    shortName: 'SEV',
    country: 'Spain',
    clubLogoUrl: 'https://cdn-team-logos.theathletic.com/cdn-cgi/image/width=48,format=auto/https://cdn-team-logos.theathletic.com/team-logo-764-300x300.png',
    stadium: 'Estadio Ramón Sánchez Pizjuán',
  },
  {
    fullName: 'Valencia FC',
    commonName: 'Valencia',
    shortName: 'VAL',
    country: 'Spain',
    clubLogoUrl: 'https://cdn-team-logos.theathletic.com/cdn-cgi/image/width=48,format=auto/https://cdn-team-logos.theathletic.com/team-logo-1212-300x300.png',
    stadium: 'Estadio de Mestalla',
  },
  {
    fullName: 'Villareal FC',
    commonName: 'Villareal',
    shortName: 'VRL',
    country: 'Spain',
    clubLogoUrl: 'https://cdn-team-logos.theathletic.com/cdn-cgi/image/width=48,format=auto/https://cdn-team-logos.theathletic.com/team-logo-1201-300x300.png',
    stadium: 'Estadio de la Cerámica',
  },
  {
    fullName: 'Paris Saint Germain FC',
    commonName: 'PSG',
    shortName: 'PSG',
    country: 'France',
    clubLogoUrl: 'https://cdn-team-logos.theathletic.com/cdn-cgi/image/width=48,format=auto/https://cdn-team-logos.theathletic.com/team-logo-661-300x300.png',
    stadium: 'Parc des Princes',
  },
  {
    fullName: 'AC Milan',
    commonName: 'Milan',
    shortName: 'ACM',
    country: 'Italy',
    clubLogoUrl: 'https://cdn-team-logos.theathletic.com/cdn-cgi/image/width=48,format=auto/https://cdn-team-logos.theathletic.com/team-logo-761-300x300.png',
    stadium: 'Stadio San Siro',
  },{
    fullName: 'FC Internazionale',
    commonName: 'Inter',
    shortName: 'INT',
    country: 'Italy',
    clubLogoUrl: 'https://cdn-team-logos.theathletic.com/cdn-cgi/image/width=48,format=auto/https://cdn-team-logos.theathletic.com/team-logo-760-300x300.png',
    stadium: 'Stadio Giuseppe Meazza',
  },{
    fullName: 'FC Juventus',
    commonName: 'Juventus',
    shortName: 'JUV',
    country: 'Italy',
    clubLogoUrl: 'https://cdn-team-logos.theathletic.com/cdn-cgi/image/width=48,format=auto/https://cdn-team-logos.theathletic.com/team-logo-660-300x300.png',
    stadium: 'Juventus Stadium',
  },
];

const clubsEngland = clubs.filter(club => club.country === 'England');
const clubsSpain = clubs.filter(club => club.country === 'Spain');
const clubsGermany = clubs.filter(club => club.country === 'Germany');
const clubsItaly = clubs.filter(club => club.country === 'Italy')

export const competitions = [
  {
    fullName: 'Premier League',
    shortName: 'EPL',
    country: 'England',
    clubs: clubsEngland,
    logoUrl: 'https://cdn-league-logos.theathletic.com/cdn-cgi/image/width=48,format=auto/https://cdn-league-logos.theathletic.com/league-6-color@2x.png',
    type: 'league',
  },
  {
    fullName: 'La Liga',
    shortName: 'La Liga',
    country: 'Spain',
    clubs: clubsSpain,
    logoUrl: 'https://cdn-league-logos.theathletic.com/cdn-cgi/image/width=48,format=auto/https://cdn-league-logos.theathletic.com/league-17-color@2x.png',
    type: 'league',
  },
  {
    fullName: 'Bundesliga',
    shortName: 'Bundesliga',
    country: 'Germany',
    clubs: clubsGermany,
    logoUrl: 'https://cdn-league-logos.theathletic.com/cdn-cgi/image/width=48,format=auto/https://cdn-league-logos.theathletic.com/league-22-color@2x.png',
    type: 'league',
  },
  {
    fullName: 'Serie A',
    shortName: 'Serie A',
    country: 'Italy',
    clubs: clubsItaly,
    logoUrl: 'https://cdn-league-logos.theathletic.com/cdn-cgi/image/width=48,format=auto/https://cdn-league-logos.theathletic.com/league-23-color@2x.png',
    type: 'league',
  },
  {
    fullName: 'Champions League',
    shortName: 'UCL',
    country: 'International',
    clubs: [],
    logoUrl: 'https://cdn-league-logos.theathletic.com/cdn-cgi/image/width=48,format=auto/https://cdn-league-logos.theathletic.com/league-7-color@2x.png',
    type: 'tournament',
  },
  {
    fullName: 'Europa League',
    shortName: 'UEL',
    country: 'International',
    clubs: [],
    logoUrl: 'https://cdn-league-logos.theathletic.com/cdn-cgi/image/width=48,format=auto/https://cdn-league-logos.theathletic.com/league-37-color@2x.png',
    type: 'tournament',
  },
  {
    fullName: 'Premier League',
    shortName: 'EPL',
    country: 'England',
    clubs: clubsEngland,
    logoUrl: 'https://cdn-league-logos.theathletic.com/cdn-cgi/image/width=48,format=auto/https://cdn-league-logos.theathletic.com/league-6-color@2x.png',
    type: 'league',
  },
  {
    fullName: 'La Liga',
    shortName: 'La Liga',
    country: 'Spain',
    clubs: clubsSpain,
    logoUrl: 'https://cdn-league-logos.theathletic.com/cdn-cgi/image/width=48,format=auto/https://cdn-league-logos.theathletic.com/league-17-color@2x.png',
    type: 'league',
  },
  {
    fullName: 'Bundesliga',
    shortName: 'Bundesliga',
    country: 'Germany',
    clubs: clubsGermany,
    logoUrl: 'https://cdn-league-logos.theathletic.com/cdn-cgi/image/width=48,format=auto/https://cdn-league-logos.theathletic.com/league-22-color@2x.png',
    type: 'league',
  },
  {
    fullName: 'Serie A',
    shortName: 'Serie A',
    country: 'Italy',
    clubs: clubsItaly,
    logoUrl: 'https://cdn-league-logos.theathletic.com/cdn-cgi/image/width=48,format=auto/https://cdn-league-logos.theathletic.com/league-23-color@2x.png',
    type: 'league',
  },
  {
    fullName: 'Champions League',
    shortName: 'UCL',
    country: 'International',
    clubs: [],
    logoUrl: 'https://cdn-league-logos.theathletic.com/cdn-cgi/image/width=48,format=auto/https://cdn-league-logos.theathletic.com/league-7-color@2x.png',
    type: 'tournament',
  },
  {
    fullName: 'Europa League',
    shortName: 'UEL',
    country: 'International',
    clubs: [],
    logoUrl: 'https://cdn-league-logos.theathletic.com/cdn-cgi/image/width=48,format=auto/https://cdn-league-logos.theathletic.com/league-37-color@2x.png',
    type: 'tournament',
  },
];


export const materials = [
  {
    author: { 
      firstName: 'Laurie',
      lastName: 'Whitwell',
      photoUrl: 'https://www.storage.com/authors/author_1.png',
      organization: 'Arsenal',
      position: 'Correspondent',
    }, 
    type: 'article',
    title: 'Arsenal’s victory over Aston Villa proves the depth of Mikel Arteta’s squad',
    content: 'As soon as Fabio Vieira released the pass, he celebrated. Emiliano Martinez had come forward for a 98th-minute corner, seeking redemption for his own goal just minutes before. The ball was headed clear by William Saliba, and Vieira raced onto it before releasing a perfect pass for Gabriel Martinelli to run through and score. A despondent Martinez barely made it back to halfway.',
    image: 'https://cdn.theathletic.com/cdn-cgi/image/width=770,format=auto/https://cdn.theathletic.com/app/uploads/2023/02/20094541/Vieira-Arsenal-Martinelli-Aston-Villa-1024x718.jpg',
    views: 76,
    likes: 74,
    publicationDate: new Date().getUTCDate().toString(),
    comments: [
      {
        user: 'John Doe', 
        message: 'Come on Arsenal!'
      }
    ],
    labels: ['Arsenal', 'Premier League', 'Aston Villa'],
  },
  {
    author: { 
      firstName: 'Laurie',
      lastName: 'Whitwell',
      photoUrl: 'https://www.storage.com/authors/author_1.png',
      organization: 'Arsenal',
      position: 'Correspondent',
    }, 
    type: 'article',
    title: 'Arsenal’s victory over Aston Villa proves the depth of Mikel Arteta’s squad',
    content: 'As soon as Fabio Vieira released the pass, he celebrated. Emiliano Martinez had come forward for a 98th-minute corner, seeking redemption for his own goal just minutes before. The ball was headed clear by William Saliba, and Vieira raced onto it before releasing a perfect pass for Gabriel Martinelli to run through and score. A despondent Martinez barely made it back to halfway.',
    image: 'https://cdn.theathletic.com/cdn-cgi/image/width=770,format=auto/https://cdn.theathletic.com/app/uploads/2023/02/20094541/Vieira-Arsenal-Martinelli-Aston-Villa-1024x718.jpg',
    views: 76,
    likes: 74,
    publicationDate: new Date().getUTCDate().toString(),
    comments: [
      {
        user: 'John Doe', 
        message: 'Come on Arsenal!'
      }
    ],
    labels: ['Arsenal', 'Premier League', 'Aston Villa'],
  },
  {
    author: { 
      firstName: 'Laurie',
      lastName: 'Whitwell',
      photoUrl: 'https://www.storage.com/authors/author_1.png',
      organization: 'Arsenal',
      position: 'Correspondent',
    }, 
    type: 'article',
    title: 'Arsenal’s victory over Aston Villa proves the depth of Mikel Arteta’s squad',
    content: 'As soon as Fabio Vieira released the pass, he celebrated. Emiliano Martinez had come forward for a 98th-minute corner, seeking redemption for his own goal just minutes before. The ball was headed clear by William Saliba, and Vieira raced onto it before releasing a perfect pass for Gabriel Martinelli to run through and score. A despondent Martinez barely made it back to halfway.',
    image: 'https://cdn.theathletic.com/cdn-cgi/image/width=770,format=auto/https://cdn.theathletic.com/app/uploads/2023/02/20094541/Vieira-Arsenal-Martinelli-Aston-Villa-1024x718.jpg',
    views: 76,
    likes: 74,
    publicationDate: new Date().getUTCDate().toString(),
    comments: [
      {
        user: 'John Doe', 
        message: 'Come on Arsenal!'
      }
    ],
    labels: ['Arsenal', 'Premier League', 'Aston Villa'],
  },
  {
    author: { 
      firstName: 'Laurie',
      lastName: 'Whitwell',
      photoUrl: 'https://www.storage.com/authors/author_1.png',
      organization: 'Arsenal',
      position: 'Correspondent',
    }, 
    type: 'article',
    title: 'Arsenal’s victory over Aston Villa proves the depth of Mikel Arteta’s squad',
    content: 'As soon as Fabio Vieira released the pass, he celebrated. Emiliano Martinez had come forward for a 98th-minute corner, seeking redemption for his own goal just minutes before. The ball was headed clear by William Saliba, and Vieira raced onto it before releasing a perfect pass for Gabriel Martinelli to run through and score. A despondent Martinez barely made it back to halfway.',
    image: 'https://cdn.theathletic.com/cdn-cgi/image/width=770,format=auto/https://cdn.theathletic.com/app/uploads/2023/02/20094541/Vieira-Arsenal-Martinelli-Aston-Villa-1024x718.jpg',
    views: 76,
    likes: 74,
    publicationDate: new Date().getUTCDate().toString(),
    comments: [
      {
        user: 'John Doe', 
        message: 'Come on Arsenal!'
      }
    ],
    labels: ['Arsenal', 'Premier League', 'Aston Villa'],
  }
];